"""
Metaflow orchestrator scaffolding tool.

Generates a complete orchestrator skeleton with all contract requirements
pre-filled and annotated.  This makes it hard to forget the requirements
that every orchestrator gets wrong the first time.

Usage:
    python -m metaflow_orchestrator_kit.scaffold my_scheduler
    metaflow-orchestrator-scaffold my_scheduler [output_dir]

This creates:
    ./<name>/
        <name>_deployer.py      DeployerImpl subclass
        <name>_objects.py       DeployedFlow / TriggeredRun subclasses
        <name>_cli.py           CLI entry-point group
        mfextinit_<name>.py     Extension registration
        ux-tests-<name>.yml     GitHub Actions workflow skeleton

The generated files compile without modification.  Replace every
# TODO: SCHEDULER API comment with real scheduler-specific code.

Each generated file references OrchestratorCapabilities (Cap) so you can
cross-check your implementation against the compliance test suite:

    from metaflow_orchestrator_kit import Cap, REQUIRED

    SUPPORTED_CAPABILITIES = REQUIRED | {Cap.NESTED_FOREACH}

    # Then run:
    python -m metaflow_orchestrator_kit.test --scheduler-type my_scheduler
"""

import os
import sys


# ---------------------------------------------------------------------------
# Template: DeployerImpl subclass
# ---------------------------------------------------------------------------

_DEPLOYER_TEMPLATE = '''\
"""
{name} deployer implementation.

Generated by: python -m metaflow_orchestrator_kit.scaffold {name}

OrchestratorCapabilities contract (DO NOT remove these comments):

  Cap.RUN_PARAMS     — run_params MUST be a list, not a tuple.
                       Click returns tuples for multi-value options.
                       Always convert with list() before passing to the scheduler API.

  Cap.PROJECT_BRANCH — --branch MUST be forwarded to every step subprocess.
                       @project reads branch_name from --branch at step runtime,
                       not just at compile time.

  Cap.CONFIG_EXPR    — METAFLOW_FLOW_CONFIG_VALUE MUST be injected into every
                       container/subprocess environment.
                       @config and @project use this env var to reconstruct the
                       config dict at task runtime.  Without it, tasks run with
                       empty/default config and @project name is wrong.

  Cap.RETRY          — retry_count MUST be derived from the scheduler\'s native
                       attempt number.  DO NOT hardcode retry_count=0.
                       Examples:
                         AWS Batch:   int(os.environ.get("AWS_BATCH_JOB_ATTEMPT", "0"))
                         Kubernetes:  derived from pod restartCount or annotation
                         Airflow:     context["ti"].try_number - 1

  Cap.FROM_DEPLOYMENT — from_deployment() must handle dotted identifiers
                        (project.branch.FlowName).  Use only the last component:
                        identifier.split(".")[-1]

See metaflow_orchestrator_kit.capabilities for the full list.
"""

import json
import os
import sys
from typing import ClassVar, Dict, List, Optional, Type

from metaflow.runner.deployer_impl import DeployerImpl

# REQUIRED: declare which capabilities this orchestrator supports.
from metaflow_orchestrator_kit import Cap, REQUIRED

SUPPORTED_CAPABILITIES = REQUIRED  # TODO: add optional caps you implement


# ---------------------------------------------------------------------------
# Compile-time helpers — called when create() is invoked, NOT at step runtime.
# ---------------------------------------------------------------------------


def _get_flow_config_value(flow) -> Optional[str]:
    """
    Extract the serialized config dict from the flow at compile time.

    REQUIRED (Cap.CONFIG_EXPR): Bake this into the workflow definition and inject
    as METAFLOW_FLOW_CONFIG_VALUE into every step subprocess env.
    Without it, @config and @project decorators use empty/default config at
    task runtime and current.branch_name is wrong.
    """
    try:
        from metaflow.flowspec import FlowStateItems
        flow_configs = flow._flow_state[FlowStateItems.CONFIGS]
        config_env = {{
            name: value
            for name, (value, _is_plain) in flow_configs.items()
            if value is not None
        }}
        if config_env:
            return json.dumps(config_env)
    except Exception:
        pass
    return None


def _get_datastore_sysroot() -> str:
    """
    Capture METAFLOW_DATASTORE_SYSROOT_LOCAL at compile (deploy) time.

    REQUIRED: Bake this into the workflow so workers write metadata to the
    same location the deployer reads from, even when the worker starts with
    a different (or absent) sysroot env var.
    """
    return os.environ.get("METAFLOW_DATASTORE_SYSROOT_LOCAL", os.path.expanduser("~"))


def _get_environment_type(environment) -> str:
    """
    Extract the environment type string from the Metaflow environment object.

    REQUIRED for @conda: pass --environment conda (or local) to every step
    subprocess so the correct Python interpreter is used.
    """
    return getattr(environment, "TYPE", "local")


class {classname}DeployerImpl(DeployerImpl):
    """
    Deployer implementation for {name}.

    Compiles the flow into a {name} workflow definition and submits it
    to the {name} scheduler.
    """

    TYPE: ClassVar[Optional[str]] = "{name}"

    def __init__(self, deployer_kwargs: Dict, **kwargs):
        # deployer_kwargs contains keyword arguments from Deployer(flow_file).{name}(...)
        # Store it before calling super().__init__ so the property works.
        self._deployer_kwargs = deployer_kwargs
        super().__init__(**kwargs)
        # TODO: SCHEDULER API — extract {name}-specific options from deployer_kwargs, e.g.:
        #   self.host = deployer_kwargs.get("host", "http://localhost:8080")
        #   self.namespace = deployer_kwargs.get("namespace", "default")

    @property
    def deployer_kwargs(self) -> Dict:
        return self._deployer_kwargs

    @staticmethod
    def deployed_flow_type() -> Type:
        from {name}_objects import {classname}DeployedFlow
        return {classname}DeployedFlow

    def create(self, **kwargs):
        return self._create(self.deployed_flow_type(), **kwargs)

    def _compile_workflow(self, flow, graph, environment, **kwargs) -> dict:
        """
        Compile the flow into a {name} workflow definition (JSON/YAML/etc).

        Called by create() with the loaded flow objects.  All compile-time
        constants MUST be captured here, NOT at step execution time.
        """
        # Capture compile-time constants — baked into the workflow definition.
        flow_config_value = _get_flow_config_value(flow)
        datastore_sysroot = _get_datastore_sysroot()
        environment_type = _get_environment_type(environment)
        flow_file = self.flow_file
        flow_name = flow.__class__.__name__

        # Extract @project branch if set
        branch = self._deployer_kwargs.get("branch") or None

        # Build the required environment for every step subprocess.
        # ALL of these must be present in every step container/process.
        required_env = {{
            # REQUIRED (Cap.CONFIG_EXPR): propagate config to step subprocesses.
            # Without this, @config/@project decorators use empty/default values.
            "METAFLOW_FLOW_CONFIG_VALUE": flow_config_value or "",

            # REQUIRED: sysroot pinned at compile time.
            "METAFLOW_DATASTORE_SYSROOT_LOCAL": datastore_sysroot,

            # REQUIRED: Metaflow metadata service URL reachable from the worker.
            "METAFLOW_SERVICE_URL": os.environ.get("METAFLOW_SERVICE_URL", ""),
            "METAFLOW_SERVICE_INTERNAL_URL": os.environ.get(
                "METAFLOW_SERVICE_INTERNAL_URL",
                os.environ.get("METAFLOW_SERVICE_URL", ""),
            ),

            # REQUIRED: PATH so conda/virtualenv binaries are found.
            "PATH": os.environ.get("PATH", ""),

                # DOCKER WORKERS NOTE: If {name} runs steps inside Docker containers,
            # the flow file path and sysroot path are host-local and will NOT exist
            # inside the container unless you mount them via docker-compose volumes.
            #
            # OPTION A (recommended for production): Build a custom worker Docker
            # image with metaflow pre-installed.  Use a shared object store (S3/MinIO)
            # as the datastore.  No volume mounts needed.
            #
            # OPTION B (local devstack only): Add volume mounts to docker-compose:
            #   volumes:
            #     - /Users:/Users   (macOS) or /home:/home (Linux)
            #     - /tmp:/tmp
            # Then set PYTHONPATH to the OSS metaflow source ONLY — do NOT pass
            # os.environ.get("PYTHONPATH", "") because that may include site-packages
            # with host-installed private extensions that fail inside the container:
            #   export PYTHONPATH=/path/to/metaflow  # OSS source only
            # If metaflow is still not importable (e.g. 'requests' missing), add a
            # pip install to the step preamble bash script:
            #   pip3 install --quiet metaflow requests
            # Note: apt-installed packages do not persist across container restarts;
            # add them to your custom Dockerfile instead for reproducibility.
            #
            # Without any fix: FileNotFoundError on flow file path, or
            # wait_for_deployed_run() polls forever (sysroot not found).
        }}

        # TODO: SCHEDULER API — build the actual workflow definition here.
        # The workflow must encode:
        #   1. The DAG structure (from `graph`)
        #   2. An "init" step that runs first:
        #          python flow.py init --run-id <run_id> --task-id 1
        #      IMPORTANT: --task-id IS required in OSS Metaflow (some forks made
        #      it optional, but OSS always requires it).  --task-id for init is 1.
        #      DO NOT pass --run-param to init: that flag is NFLX-only and does not
        #      exist in OSS Metaflow.  Parameters in OSS are resolved during step
        #      execution, not during init.
        #   3. For each step: the command (see _build_step_command below)
        #   4. required_env injected into every step container/process env
        #   5. branch stored so it can be passed to each step command
        #
        # FLOW PARAMETERS in OSS Metaflow:
        #   Flow parameters are passed to the start step via environment variables,
        #   not via --run-param in the init command.  Set these env vars for the
        #   step that executes the @Parameter fields:
        #       METAFLOW_PARAMETER_<NAME>=<value>   (one per parameter)
        #   Example: a flow with @Parameter("alpha", default=0.5) needs:
        #       export METAFLOW_PARAMETER_ALPHA="0.9"   # override at trigger time
        #   These must be injected into the step container environment for the
        #   start step (and any step that reads parameters).
        #
        # DOCKER WORKERS — inter-step data passing:
        #   Each step runs in a separate container; /tmp is NOT shared between steps.
        #   Do not write run_id or other coordination data to /tmp files.
        #   Use the scheduler's native inter-step mechanism (return values,
        #   environment variable injection, or a shared external store) to pass
        #   the run_id from the init step to subsequent steps.
        #   Example (Windmill): the init bash module prints the run_id as its last
        #   line; subsequent modules access it via results.<init_module_id>.

        return {{
            "flow_name": flow_name,
            "flow_file": flow_file,
            "environment_type": environment_type,
            "datastore_sysroot": datastore_sysroot,
            "flow_config_value": flow_config_value,
            "branch": branch,
            "required_env": required_env,
            # TODO: SCHEDULER API — add scheduler-specific fields
        }}

    def _build_step_command(
        self,
        step_name: str,
        run_id: str,
        task_id: str,
        input_paths: str,
        branch: Optional[str] = None,
        retry_count: int = 0,  # REQUIRED (Cap.RETRY): derive from scheduler attempt
        environment_type: str = "local",
        flow_file: Optional[str] = None,
    ) -> List[str]:
        """
        Build the command list to execute one Metaflow step.

        REQUIRED (Cap.PROJECT_BRANCH):
            --branch MUST be included when branch is not None.
            @project reads branch_name from --branch at step runtime.
            Omitting --branch causes current.branch_name to be empty.

        REQUIRED (Cap.RETRY):
            retry_count MUST come from the scheduler native attempt counter.
            DO NOT leave retry_count=0.
            Examples by scheduler:
              AWS Batch:   int(os.environ.get("AWS_BATCH_JOB_ATTEMPT", "0"))
              Kubernetes:  from pod annotation or restart count
              Airflow:     context["ti"].try_number - 1
              Prefect:     ctx.task_run.run_count - 1

        REQUIRED (environment_type):
            Pass --environment so the correct Python is used for @conda flows.

        OPTIONAL (Cap.CONDA) — two approaches depending on executor type:

        APPROACH A — subprocess-based orchestrators (standard):
            Pass --environment conda (or whatever environment_type is).
            Metaflow\'s built-in task runner calls conda_decorator.runtime_init()
            automatically when the step subprocess starts.  runtime_init()
            extracts the code package into a temp dir and adds it to PYTHONPATH.
            No additional work needed.  This is what the code below does.

        APPROACH B — in-process executors (Dagster execute_job, Windmill sync,
            Mage, or any orchestrator that runs steps without re-entering the
            Metaflow subprocess runtime):
            runtime_init() is NEVER called, so:
              - _metaflow_home is None
              - The code package is never extracted
              - conda-installed packages are NOT on PYTHONPATH
              - Steps fail with ModuleNotFoundError for any conda package

            FIX: use "conda run -n <env_name>" to wrap the step command.
            conda run activates the named environment before launching the
            process, setting PYTHONPATH, sys.executable, and native library
            paths automatically.

        APPROACH C — Docker workers that run bash scripts (Windmill, Prefect):
            The step command runs inside a Docker container that may not have
            metaflow installed.  The recommended pattern for the bash preamble
            of each step script:

                # In the bash script emitted by _compile_workflow():
                set -e
                if ! python3 -c "import metaflow" 2>/dev/null; then
                    pip3 install --quiet metaflow requests
                fi
                export METAFLOW_DATASTORE_SYSROOT_LOCAL={datastore_sysroot!r}
                export METAFLOW_FLOW_CONFIG_VALUE={flow_config_value!r}
                python3 {flow_file} ...

            This is more robust than relying on PYTHONPATH pointing to a
            host-mounted source tree, which exposes unintended extensions.

            If your orchestrator uses Approach B, replace the cmd construction
            below with:
                if environment_type == "conda" and conda_env_name:
                    cmd = [
                        "conda", "run", "--no-capture-output",
                        "-n", conda_env_name,
                        "python",
                    ]
                else:
                    cmd = [sys.executable]

            See: metaflow/plugins/pypi/conda_decorator.py CondaStepDecorator.runtime_init()
        """
        flow_file = flow_file or self.flow_file
        cmd = [
            sys.executable, flow_file,
            "--no-pylint",
            "--environment", environment_type,
            "--metadata", "service",
        ]

        if branch:
            # REQUIRED (Cap.PROJECT_BRANCH): DO NOT REMOVE — forward --branch to
            # every step subprocess so @project reads the correct branch_name.
            cmd += ["--branch", branch]

        # IMPORTANT: --tag must come AFTER the "step" subcommand, not before it.
        # Metaflow's top-level CLI does not accept --tag as a global flag; it is
        # only valid as an argument to "step", "run", "init", etc.
        # Wrong:  python flow.py --tag foo step start ...
        # Correct: python flow.py step start --tag foo ...
        #
        # IMPORTANT: --input-paths is REQUIRED for every step including "start".
        # Without it, steps fail with:
        #   UnboundLocalError: cannot access local variable 'inputs'
        # Input path format: "{run_id}/{parent_step}/{parent_task_id}"
        # For the start step (parent is init):  "{run_id}/_parameters/1"
        # For other steps (parent is previous): "{run_id}/{parent_step}/1"
        # For join steps (multiple parents):    "A/{s1}/1,A/{s2}/1,..."  (comma-separated)
        cmd += [
            "step", step_name,
            "--run-id", run_id,
            "--task-id", task_id,
            "--retry-count", str(retry_count),  # TODO: SCHEDULER API — replace 0 with scheduler attempt
            "--input-paths", input_paths,  # REQUIRED: see format notes above
            # TODO: SCHEDULER API — add --tag options here (after "step <name>"), not before:
            #   for tag in tags:
            #       cmd += ["--tag", tag]
        ]

        return cmd
'''


# ---------------------------------------------------------------------------
# Template: DeployedFlow / TriggeredRun objects
# ---------------------------------------------------------------------------

_OBJECTS_TEMPLATE = '''\
"""
{name} DeployedFlow and TriggeredRun objects.

Generated by: python -m metaflow_orchestrator_kit.scaffold {name}
"""

import os
from typing import Any, ClassVar, Dict, List, Optional

from metaflow.runner.deployer import DeployedFlow, TriggeredRun


class {classname}TriggeredRun(TriggeredRun):
    """Represents a single triggered execution of a {name} workflow."""

    @property
    def status(self) -> Optional[str]:
        """
        Return the current run status.

        MUST return one of: None, "RUNNING", "SUCCEEDED", "FAILED", "TIMED_OUT",
        "ABORTED" (case-insensitive check in wait_for_deployed_run).

        Return None when the run has not started yet.
        """
        # TODO: SCHEDULER API — query {name} for the current execution status
        raise NotImplementedError

    def terminate(self, **kwargs) -> bool:
        """Terminate the running execution. Return True if successful."""
        # TODO: SCHEDULER API — call {name} API to stop the execution
        raise NotImplementedError


class {classname}DeployedFlow(DeployedFlow):
    """Represents a deployed {name} workflow (analogous to a DAG or state machine)."""

    TYPE: ClassVar[Optional[str]] = "{name}"

    def trigger(
        self,
        run_params: Optional[List[str]] = None,
        **kwargs: Any,
    ) -> {classname}TriggeredRun:
        """
        Trigger a new run of the deployed workflow.

        REQUIRED (Cap.RUN_PARAMS): run_params MUST be a list, not a tuple.
        Click returns tuples for multi-value options; always convert:
            run_params = list(run_params) if run_params else []
        Passing a tuple raises TypeError inside most scheduler client libraries.
        """
        # REQUIRED (Cap.RUN_PARAMS): must be list, not tuple — DO NOT REMOVE
        run_params = list(run_params) if run_params else []

        # TODO: SCHEDULER API — call {name} API to start a new execution.
        # Steps to complete:
        #   1. Generate a Metaflow run_id (e.g. "{name}-" + str(uuid.uuid4())[:12])
        #   2. Trigger the {name} execution, forwarding run_params as flow parameters
        #   3. Return a {classname}TriggeredRun with the pathspec set:
        #        pathspec = f"{{self.deployer.flow_name}}/{{run_id}}"
        raise NotImplementedError

    @classmethod
    def from_deployment(cls, identifier: str, **kwargs) -> "{classname}DeployedFlow":
        """
        Recover a previously deployed workflow by its identifier.

        REQUIRED (Cap.FROM_DEPLOYMENT):
            identifier may be a dotted name (project.branch.FlowName).
            Use only the last component as the Python class name:
                flow_name = identifier.split(".")[-1]
            Using the full dotted string as a class name raises SyntaxError.
        """
        # REQUIRED (Cap.FROM_DEPLOYMENT): handle dotted names — DO NOT REMOVE
        flow_name = identifier.split(".")[-1]

        # TODO: SCHEDULER API — look up the {name} workflow by identifier
        # and return a {classname}DeployedFlow instance.
        raise NotImplementedError
'''


# ---------------------------------------------------------------------------
# Template: CLI entry point
# ---------------------------------------------------------------------------

_CLI_TEMPLATE = '''\
"""
{name} CLI group for Metaflow.

Generated by: python -m metaflow_orchestrator_kit.scaffold {name}

This group is registered via mfextinit_{name}.py so that
`python flow.py {name} ...` works after the extension is installed.
"""

import click


@click.group()
def cli():
    """Commands for managing {name} deployments."""
    pass


@cli.command()
@click.option("--tags", multiple=True, help="Tags to apply to the deployment.")
@click.option(
    "--deployer-attribute-file",
    default=None,
    help="Internal: path to write deployment attributes JSON.",
)
def create(tags, deployer_attribute_file):
    """Deploy the flow to {name}."""
    # REQUIRED: after successful deployment, write a JSON file to
    # deployer_attribute_file with at least:
    #   {{"name": "<workflow_id>", "flow_name": "<FlowClass>"}}
    # This is how the Deployer API learns the deployed workflow name.
    #
    # TODO: SCHEDULER API — compile workflow definition and submit to {name}
    raise NotImplementedError("create() not yet implemented")


@cli.command()
def delete():
    """Remove a {name} deployment."""
    raise NotImplementedError("delete() not yet implemented")


@cli.command()
def list():
    """List {name} deployments for this flow."""
    raise NotImplementedError("list() not yet implemented")


@cli.command()
@click.option("--name", required=True, help="Deployment name to trigger.")
@click.option("--run-param", multiple=True, help="Flow parameter as key=value.")
@click.option(
    "--deployer-attribute-file",
    default=None,
    help="Internal: path to write trigger attributes JSON.",
)
def trigger(name, run_param, deployer_attribute_file):
    """Trigger a run of a deployed {name} workflow."""
    import json as _json
    import requests as _requests

    # REQUIRED (Cap.RUN_PARAMS): run_param arrives as a tuple from Click.
    # Convert to list before using:
    run_params = list(run_param)

    # TODO: SCHEDULER API — trigger the workflow named `name` with `run_params`.
    # Replace this example request with the real {name} API call:
    #   resp = _requests.post(f"http://localhost:8080/api/pipelines/{{name}}/trigger", ...)
    #   resp.raise_for_status()
    resp = None  # TODO: SCHEDULER API — replace with real request

    # AUTH TOKEN NOTE: If {name} uses short-lived tokens (e.g. session tokens),
    # this token may have expired by the time trigger() is called after a long
    # create() step.  Use a service-account / long-lived token in CI, or
    # fetch a fresh token here rather than reading from config.
    # Windmill example: Settings > Users & Tokens > Tokens > Add token (no expiry).

    # Always log the full response when debugging so you can see the exact key names.
    # Run with: METAFLOW_DEBUG_DEPLOYER=1 python flow.py {name} trigger ...
    if resp is not None:
        try:
            response_data = resp.json()
        except Exception:
            response_data = {{"raw": resp.text}}
    else:
        response_data = {{}}

    if os.environ.get("METAFLOW_DEBUG_DEPLOYER"):
        print(
            f"[DEBUG] {name} trigger response: {{_json.dumps(response_data, indent=2)}}",
            file=sys.stderr,
        )

    # TODO: SCHEDULER API — extract run_id from response_data.
    # The exact key depends on your scheduler.  Common patterns:
    #   Kestra:  response_data["id"]                       (raises KeyError if missing — good)
    #   Prefect: response_data["id"]
    #   Mage:    response_data["pipeline_run"]["id"]        (nested)
    #   Windmill:response_data["run_id"]
    #
    # IMPORTANT: use direct key access (response_data["id"]) rather than .get("id")
    # so that a wrong key raises KeyError immediately instead of silently returning None,
    # which causes confusing failures later (e.g. pathspec "FlowName/None").
    #
    # Print the full response first with METAFLOW_DEBUG_DEPLOYER=1 to discover the keys.
    run_id = None  # TODO: SCHEDULER API — replace with response_data["<key>"]

    # CRITICAL ORDER: write deployer_attribute_file BEFORE executing steps.
    # Metaflow's Deployer.trigger() blocks waiting for this file to appear.
    # If you write it AFTER steps complete, the deployer blocks for the full
    # flow execution time, causing test timeouts (pytest --timeout killed the
    # subprocess before it could write the file).
    #
    # Write the file immediately with at least: {{"pathspec": "<FlowName>/<run_id>"}}
    # so that handle_timeout returns quickly, then execute steps.
    #
    # TODO: SCHEDULER API — replace this with real values:
    import json as _json, uuid as _uuid, os as _os
    run_id = "TODO_SCHEDULER_run_" + _uuid.uuid4().hex[:12]  # TODO: SCHEDULER API
    flow_name = "TODO_FLOW_NAME"  # TODO: SCHEDULER API — get from config
    pathspec = f"{{flow_name}}/{{run_id}}"

    # Write the attribute file FIRST — do not move this after step execution.
    if deployer_attribute_file:
        with open(deployer_attribute_file, "w") as _f:
            _json.dump({{"pathspec": pathspec}}, _f)

    # TODO: SCHEDULER API — now trigger the workflow named `name` with `run_params`.
    # The step execution can happen synchronously or asynchronously after this point.
    raise NotImplementedError("trigger() scheduler API call not yet implemented")
'''


# ---------------------------------------------------------------------------
# Template: mfextinit registration file
# ---------------------------------------------------------------------------

_MFEXTINIT_TEMPLATE = '''\
"""Metaflow extension registration for {name}.

Metaflow discovers this file automatically via the ``metaflow_extensions``
namespace package mechanism (it scans for ``mfextinit_*.py`` files in any
installed package under the ``metaflow_extensions`` namespace).

Place this file at:
    metaflow_extensions/{name}/plugins/mfextinit_{name}.py

After ``pip install -e .`` the following becomes available:
  - ``python flow.py {name} create ...`` (CLI)
  - ``Deployer(flow_file).{name}(...)`` (Python API)
  - ``--scheduler-type={name}`` in UX tests

Reference: https://docs.metaflow.org/internals/extensions
"""

# Register the CLI group: ``python flow.py {name} create ...``
CLIS_DESC = [
    ("{name}", ".{name}.{name}_cli.cli"),
]

# Register the DeployerImpl subclass so ``Deployer(flow_file).{name}()`` works.
# The string is a dotted import path relative to this package\'s ``plugins/`` directory.
DEPLOYER_IMPL_PROVIDERS_DESC = [
    ("{name}", ".{name}.{name}_deployer.{classname}DeployerImpl"),
]

# Register the step decorator used for internal runtime tracking (optional).
# Uncomment and implement if your orchestrator needs to inject state into steps.
STEP_DECORATORS_DESC = [
    # ("{name}_internal", ".{name}.{name}_decorator.{classname}InternalDecorator"),
]
'''


# ---------------------------------------------------------------------------
# Template: GitHub Actions workflow
# ---------------------------------------------------------------------------

_GHA_TEMPLATE = """\
name: UX Tests - {name}

# Compliance and integration tests for the {name} orchestrator.
# Generated by: python -m metaflow_orchestrator_kit.scaffold {name}
#
# Add this workflow to .github/workflows/ after wiring up the devstack.
# The compliance tests require metaflow-orchestrator-kit as a test dependency.

on:
  push:
    branches:
      - master
      - "**/{name}/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ux-tests:
    name: "{name} UX tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Runner (local) backend -- always included
          - backend: local
            services: "minio,postgresql,metadata-service"
            workers: 4

          # {name} backend -- add the services your scheduler needs
          - backend: {name}
            services: "minio,postgresql,metadata-service"  # TODO: add {name} service
            workers: 4

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Metaflow and test dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]" metaflow-orchestrator-kit pytest-xdist pytest-timeout pytest-cov

      - name: Set up minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cpus: 2
          memory: 6144

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install Tilt
        run: |
          curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh \\
            | VERSION=v0.33.11 bash

      - name: Start devstack
        working-directory: devtools
        run: |
          mkdir -p .devtools
          SERVICES="${{ matrix.services }}" \\
            tilt up --stream 2>&1 | tee /tmp/tilt.log &
          for i in $(seq 1 60); do
            tilt get session >/dev/null 2>&1 && break
            sleep 2
          done
          tilt wait --for=condition=Ready "uiresource/(Tiltfile)" --timeout=120s
          tilt wait --for=condition=Ready uiresource/generate-configs --timeout=1800s

      - name: Start minikube tunnel
        run: sudo minikube tunnel &

      - name: Run compliance tests - ${{ matrix.backend }}
        run: |
          AWS_SHARED_CREDENTIALS_FILE="" \\
          PYTHONPATH=$PWD \\
          python -m pytest \\
            metaflow_orchestrator_kit/compliance/ \\
            test/ux/core/test_basic.py \\
            test/ux/core/test_config.py \\
            test/ux/core/test_dag.py \\
            -m "not conda" \\
            --ux-config=test/ux/ux_test_config.yaml \\
            --only-backend "${{ matrix.backend }}" \\
            -n ${{ matrix.workers }} \\
            -v \\
            --tb=short \\
            --timeout=1800 \\
            --cov=metaflow \\
            --cov-report=xml:coverage.xml \\
            --junit-xml=junit-${{ matrix.backend }}.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.backend }}
          path: coverage.xml
          if-no-files-found: ignore
          include-hidden-files: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.backend }}
          path: junit-${{ matrix.backend }}.xml
          if-no-files-found: ignore
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def _classname(name: str) -> str:
    """Convert snake_case or kebab-case to PascalCase."""
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_"))


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


def scaffold(name: str, output_dir: str = ".") -> None:
    """Generate orchestrator skeleton files for the given scheduler name."""
    cls = _classname(name)
    subdir = os.path.join(output_dir, name)

    files = {
        os.path.join(subdir, f"{name}_deployer.py"): _DEPLOYER_TEMPLATE.format(name=name, classname=cls),
        os.path.join(subdir, f"{name}_objects.py"): _OBJECTS_TEMPLATE.format(name=name, classname=cls),
        os.path.join(subdir, f"{name}_cli.py"): _CLI_TEMPLATE.format(name=name, classname=cls),
        os.path.join(subdir, f"mfextinit_{name}.py"): _MFEXTINIT_TEMPLATE.format(name=name, classname=cls),
        os.path.join(subdir, f"ux-tests-{name}.yml"): _GHA_TEMPLATE.format(name=name, classname=cls),
    }

    print(f"Scaffolding orchestrator: {name!r} (class prefix: {cls})")
    print(f"Output directory: {os.path.abspath(subdir)}/")
    print()
    for filepath, content in files.items():
        _write(filepath, content)

    print()
    print("=" * 60)
    print("Next steps:")
    print("=" * 60)
    print()
    print(f"  1. cd {name}/")
    print()
    print(f"  2. Fill in all # TODO: SCHEDULER API sections in:")
    print(f"       {name}_deployer.py  - _compile_workflow(), _build_step_command()")
    print(f"       {name}_objects.py   - trigger(), from_deployment(), status")
    print(f"       {name}_cli.py       - create(), trigger()")
    print()
    print(f"  3. Place generated files in your extension package:")
    print(f"       metaflow_extensions/{name}/plugins/{name}/  <- deployer, objects, cli")
    print(f"       metaflow_extensions/{name}/plugins/mfextinit_{name}.py")
    print()
    print("  *** CRITICAL: metaflow_extensions/ must NOT have __init__.py ***")
    print("      It is an implicit namespace package. Adding __init__.py breaks")
    print(f"      extension discovery — Deployer(flow).{name}() will silently not exist.")
    print()
    print(f"  4. Validate the implementation (catches common bugs without running tests):")
    print(f"       python -m metaflow_orchestrator_kit.validate ./{name}/")
    print()
    print(f"  5. Run the compliance tests:")
    print(f"       python -m metaflow_orchestrator_kit.test \\")
    print(f"         --scheduler-type {name} \\")
    print(f"         --deploy-args host=http://localhost:8080")
    print()
    print("Contract checklist (things every orchestrator gets wrong):")
    print("  [ ] run_params is list (not tuple) in trigger()              [Cap.RUN_PARAMS]")
    print("  [ ] --branch forwarded to every step subprocess              [Cap.PROJECT_BRANCH]")
    print("  [ ] METAFLOW_FLOW_CONFIG_VALUE injected into container env   [Cap.CONFIG_EXPR]")
    print("  [ ] retry_count derived from scheduler native attempt        [Cap.RETRY]")
    print("  [ ] from_deployment handles dotted identifiers               [Cap.FROM_DEPLOYMENT]")
    print("  [ ] METAFLOW_DATASTORE_SYSROOT_LOCAL captured at compile time")
    print("  [ ] --environment passed to step command (for @conda)")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("Usage: python -m metaflow_orchestrator_kit.scaffold <name> [output_dir]")
        sys.exit(1)

    name = sys.argv[1].replace("-", "_")
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    scaffold(name, output_dir)


if __name__ == "__main__":
    main()
